[package]
name = "mike_core"
version = "0.1.0"
authors = ["Danila Krapivenko"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
rpi_embedded = "0.1.0"
rppal = "0.13.1"
pid = "3.0.0"